version: "3.9"  # optional since v1.27.0
services:
  cassandra:
    container_name: "cassandra"
    image: cassandra
    ports:
      - "9042:9042"
    restart: always
    networks:
      - network
    environment:
      # important: broadcast address must be set to the Docker hostname
      - CASSANDRA_BROADCAST_ADDRESS=cassandra
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_REMOTE_CONNECTION=false
      - CASSANDRA_START_RPC=true
  zookeeper:
    container_name: "zookeeper"
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    restart: always
    networks:
      - network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: "kafka"
    image: 'bitnami/kafka:latest'
    restart: always
    networks:
      - network
    ports:
      - '9092:9092'


    environment:
      ALLOW_PLAINTEXT_LISTENER: true
      KAFKA_HOST_NAME: kafka
      KAFKA_PORT: 9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME:-kafka}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

volumes:
  logvolume01: {}

networks:
  network:
    driver: bridge